package com.sns.scout.managers;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;

   
      
   
/**
 * This class was autogenerated by Torque on:
 *
 * [Tue Jan 19 16:39:36 CST 2010]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Tasklinks
 */
public abstract class BaseTasklinks extends BaseObject
{
    /** The Peer class */
    private static final TasklinksPeer peer =
        new TasklinksPeer();

                  
        /**
         * The value for the linkid field
         */
        private int linkid;
              
        /**
         * The value for the firstid field
         */
        private int firstid;
              
        /**
         * The value for the nextid field
         */
        private int nextid;
      
      
        /**
         * Get the Linkid
         *
         * @return int
         */
        public int getLinkid()
        {
            return linkid;
        }

                                            
        /**
         * Set the value of Linkid
         *
         * @param v new value
         */
        public void setLinkid(int v) 
        {
          


         if (this.linkid != v)
        {
             this.linkid = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Firstid
         *
         * @return int
         */
        public int getFirstid()
        {
            return firstid;
        }

                                                      
        /**
         * Set the value of Firstid
         *
         * @param v new value
         */
        public void setFirstid(int v) throws TorqueException
        {
          


         if (this.firstid != v)
        {
             this.firstid = v;
            setModified(true);
        }

                                                                                                                
                if (aTaskRelatedByFirstid != null && !(aTaskRelatedByFirstid.getTaskid()==v))
                {
            aTaskRelatedByFirstid = null;
        }
          
                       }


        /**
         * Get the Nextid
         *
         * @return int
         */
        public int getNextid()
        {
            return nextid;
        }

                                                      
        /**
         * Set the value of Nextid
         *
         * @param v new value
         */
        public void setNextid(int v) throws TorqueException
        {
          


         if (this.nextid != v)
        {
             this.nextid = v;
            setModified(true);
        }

                                                                                                                
                if (aTaskRelatedByNextid != null && !(aTaskRelatedByNextid.getTaskid()==v))
                {
            aTaskRelatedByNextid = null;
        }
          
                       }


 
     
   
                 
      
       private Task aTaskRelatedByFirstid;

    /**
     * Declares an association between this object and a Task object
     *
     * @param v Task
     * @throws TorqueException
     */
    public void setTaskRelatedByFirstid(Task v) throws TorqueException
    {
           if (v == null)
        {
                        setFirstid(0);
                    }
        else
        {
            setFirstid(v.getTaskid());
        }
           aTaskRelatedByFirstid = v;
    }

                 
    /**
     * Get the associated Task object
     *
     * @return the associated Task object
     * @throws TorqueException
     */
    public Task getTaskRelatedByFirstid() throws TorqueException
    {
        if (aTaskRelatedByFirstid == null && (this.firstid > 0))
        {
              aTaskRelatedByFirstid = TaskPeer.retrieveByPK(SimpleKey.keyFor(this.firstid));
      
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               Task obj = TaskPeer.retrieveByPK(this.firstid);
               obj.addTasklinkssRelatedByFirstid(this);
             */
        }
        return aTaskRelatedByFirstid;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setTaskRelatedByFirstidKey(ObjectKey key) throws TorqueException
    {
    
                                        setFirstid(((NumberKey) key).intValue());
                    }
 
   
                 
      
       private Task aTaskRelatedByNextid;

    /**
     * Declares an association between this object and a Task object
     *
     * @param v Task
     * @throws TorqueException
     */
    public void setTaskRelatedByNextid(Task v) throws TorqueException
    {
           if (v == null)
        {
                        setNextid(0);
                    }
        else
        {
            setNextid(v.getTaskid());
        }
           aTaskRelatedByNextid = v;
    }

                 
    /**
     * Get the associated Task object
     *
     * @return the associated Task object
     * @throws TorqueException
     */
    public Task getTaskRelatedByNextid() throws TorqueException
    {
        if (aTaskRelatedByNextid == null && (this.nextid > 0))
        {
              aTaskRelatedByNextid = TaskPeer.retrieveByPK(SimpleKey.keyFor(this.nextid));
      
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               Task obj = TaskPeer.retrieveByPK(this.nextid);
               obj.addTasklinkssRelatedByNextid(this);
             */
        }
        return aTaskRelatedByNextid;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setTaskRelatedByNextidKey(ObjectKey key) throws TorqueException
    {
    
                                        setNextid(((NumberKey) key).intValue());
                    }
    
        
    
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
      if (fieldNames == null)
      {
        fieldNames = new ArrayList();
            fieldNames.add("Linkid");
            fieldNames.add("Firstid");
            fieldNames.add("Nextid");
            fieldNames = Collections.unmodifiableList(fieldNames);
      }
      return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
            if (name.equals("Linkid"))
    {
              return new Integer(getLinkid());
          }
            if (name.equals("Firstid"))
    {
              return new Integer(getFirstid());
          }
            if (name.equals("Nextid"))
    {
              return new Integer(getNextid());
          }
            return null;
    }
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
            if (name.equals(TasklinksPeer.LINKID))
        {
              return new Integer(getLinkid());
          }
            if (name.equals(TasklinksPeer.FIRSTID))
        {
              return new Integer(getFirstid());
          }
            if (name.equals(TasklinksPeer.NEXTID))
        {
              return new Integer(getNextid());
          }
            return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
    {
              return new Integer(getLinkid());
          }
            if (pos == 1)
    {
              return new Integer(getFirstid());
          }
            if (pos == 2)
    {
              return new Integer(getNextid());
          }
                return null;
    }

     


    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
             save(TasklinksPeer.getMapBuilder()
                .getDatabaseMap().getName());
     }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
         try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }

     }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;



  
        // If this object has been modified, then save it to the database.
        if (isModified())
        {
            if (isNew())
            {
                TasklinksPeer.doInsert((Tasklinks) this, con);
                setNew(false);
            }
            else
            {
                TasklinksPeer.doUpdate((Tasklinks) this, con);
            }
        }

              alreadyInSave = false;
      }
      }


                
    
    

        /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  linkid ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        
    {
                    setLinkid(((NumberKey) key).intValue());
            }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) 
    {
                    setLinkid(Integer.parseInt(key));
            }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getLinkid());
    }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Tasklinks copy() throws TorqueException
    {
        return copyInto(new Tasklinks());
    }

    protected Tasklinks copyInto(Tasklinks copyObj) throws TorqueException
    {
        copyObj.setLinkid(linkid);
        copyObj.setFirstid(firstid);
        copyObj.setNextid(nextid);

                      copyObj.setLinkid(0);
                    

  
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public TasklinksPeer getPeer()
    {
        return peer;
    }
}
