package com.sns.scout.managers;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;

   
   
/**
 * This class was autogenerated by Torque on:
 *
 * [Tue Jan 19 16:39:36 CST 2010]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Tasknotes
 */
public abstract class BaseTasknotes extends BaseObject
{
    /** The Peer class */
    private static final TasknotesPeer peer =
        new TasknotesPeer();

                  
        /**
         * The value for the noteid field
         */
        private int noteid;
              
        /**
         * The value for the taskid field
         */
        private int taskid;
              
        /**
         * The value for the notedate field
         */
        private Date notedate;
              
        /**
         * The value for the detail field
         */
        private String detail;
      
      
        /**
         * Get the Noteid
         *
         * @return int
         */
        public int getNoteid()
        {
            return noteid;
        }

                                            
        /**
         * Set the value of Noteid
         *
         * @param v new value
         */
        public void setNoteid(int v) 
        {
          


         if (this.noteid != v)
        {
             this.noteid = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Taskid
         *
         * @return int
         */
        public int getTaskid()
        {
            return taskid;
        }

                                                      
        /**
         * Set the value of Taskid
         *
         * @param v new value
         */
        public void setTaskid(int v) throws TorqueException
        {
          


         if (this.taskid != v)
        {
             this.taskid = v;
            setModified(true);
        }

                                          
                if (aTask != null && !(aTask.getTaskid()==v))
                {
            aTask = null;
        }
          
                       }


        /**
         * Get the Notedate
         *
         * @return Date
         */
        public Date getNotedate()
        {
            return notedate;
        }

                                            
        /**
         * Set the value of Notedate
         *
         * @param v new value
         */
        public void setNotedate(Date v) 
        {
          


         if (!ObjectUtils.equals(this.notedate, v))
        {
             this.notedate = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Detail
         *
         * @return String
         */
        public String getDetail()
        {
            return detail;
        }

                                            
        /**
         * Set the value of Detail
         *
         * @param v new value
         */
        public void setDetail(String v) 
        {
          


         if (!ObjectUtils.equals(this.detail, v))
        {
             this.detail = v;
            setModified(true);
        }

                  
                       }


 
     
   
             
   
       private Task aTask;

    /**
     * Declares an association between this object and a Task object
     *
     * @param v Task
     * @throws TorqueException
     */
    public void setTask(Task v) throws TorqueException
    {
           if (v == null)
        {
                        setTaskid(0);
                    }
        else
        {
            setTaskid(v.getTaskid());
        }
           aTask = v;
    }

                 
    /**
     * Get the associated Task object
     *
     * @return the associated Task object
     * @throws TorqueException
     */
    public Task getTask() throws TorqueException
    {
        if (aTask == null && (this.taskid > 0))
        {
              aTask = TaskPeer.retrieveByPK(SimpleKey.keyFor(this.taskid));
      
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               Task obj = TaskPeer.retrieveByPK(this.taskid);
               obj.addTasknotess(this);
             */
        }
        return aTask;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setTaskKey(ObjectKey key) throws TorqueException
    {
    
                                        setTaskid(((NumberKey) key).intValue());
                    }
    
        
    
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
      if (fieldNames == null)
      {
        fieldNames = new ArrayList();
            fieldNames.add("Noteid");
            fieldNames.add("Taskid");
            fieldNames.add("Notedate");
            fieldNames.add("Detail");
            fieldNames = Collections.unmodifiableList(fieldNames);
      }
      return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
            if (name.equals("Noteid"))
    {
              return new Integer(getNoteid());
          }
            if (name.equals("Taskid"))
    {
              return new Integer(getTaskid());
          }
            if (name.equals("Notedate"))
    {
              return getNotedate();
          }
            if (name.equals("Detail"))
    {
              return getDetail();
          }
            return null;
    }
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
            if (name.equals(TasknotesPeer.NOTEID))
        {
              return new Integer(getNoteid());
          }
            if (name.equals(TasknotesPeer.TASKID))
        {
              return new Integer(getTaskid());
          }
            if (name.equals(TasknotesPeer.NOTEDATE))
        {
              return getNotedate();
          }
            if (name.equals(TasknotesPeer.DETAIL))
        {
              return getDetail();
          }
            return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
    {
              return new Integer(getNoteid());
          }
            if (pos == 1)
    {
              return new Integer(getTaskid());
          }
            if (pos == 2)
    {
              return getNotedate();
          }
            if (pos == 3)
    {
              return getDetail();
          }
                return null;
    }

     


    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
             save(TasknotesPeer.getMapBuilder()
                .getDatabaseMap().getName());
     }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
         try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }

     }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;



  
        // If this object has been modified, then save it to the database.
        if (isModified())
        {
            if (isNew())
            {
                TasknotesPeer.doInsert((Tasknotes) this, con);
                setNew(false);
            }
            else
            {
                TasknotesPeer.doUpdate((Tasknotes) this, con);
            }
        }

              alreadyInSave = false;
      }
      }


                
    
    

        /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  noteid ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        
    {
                    setNoteid(((NumberKey) key).intValue());
            }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) 
    {
                    setNoteid(Integer.parseInt(key));
            }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getNoteid());
    }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Tasknotes copy() throws TorqueException
    {
        return copyInto(new Tasknotes());
    }

    protected Tasknotes copyInto(Tasknotes copyObj) throws TorqueException
    {
        copyObj.setNoteid(noteid);
        copyObj.setTaskid(taskid);
        copyObj.setNotedate(notedate);
        copyObj.setDetail(detail);

                      copyObj.setNoteid(0);
                        

  
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public TasknotesPeer getPeer()
    {
        return peer;
    }
}
