package com.sns.scout.managers;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;


/**
 * This class was autogenerated by Torque on:
 *
 * [Tue Jan 19 16:39:36 CST 2010]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Project
 */
public abstract class BaseProject extends BaseObject
{
    /** The Peer class */
    private static final ProjectPeer peer =
        new ProjectPeer();

                  
        /**
         * The value for the projectid field
         */
        private int projectid;
                                                                                      
        /**
         * The value for the name field
         */
        private String name = "";
              
        /**
         * The value for the startdate field
         */
        private Date startdate;
              
        /**
         * The value for the created field
         */
        private Date created;
      
      
        /**
         * Get the Projectid
         *
         * @return int
         */
        public int getProjectid()
        {
            return projectid;
        }

                                                                              
        /**
         * Set the value of Projectid
         *
         * @param v new value
         */
        public void setProjectid(int v) throws TorqueException
        {
          


         if (this.projectid != v)
        {
             this.projectid = v;
            setModified(true);
        }

                  
                                                  
              // update associated Task
              if (collTasks != null)
              {
                  for (int i = 0; i < collTasks.size(); i++)
                  {
                      ((Task) collTasks.get(i))
                          .setProjectid(v);
                  }
              }
                                                              
              // update associated Todo
              if (collTodos != null)
              {
                  for (int i = 0; i < collTodos.size(); i++)
                  {
                      ((Todo) collTodos.get(i))
                          .setProjectid(v);
                  }
              }
                                                              
              // update associated Userproject
              if (collUserprojects != null)
              {
                  for (int i = 0; i < collUserprojects.size(); i++)
                  {
                      ((Userproject) collUserprojects.get(i))
                          .setProjectid(v);
                  }
              }
                                                              
              // update associated Groupproject
              if (collGroupprojects != null)
              {
                  for (int i = 0; i < collGroupprojects.size(); i++)
                  {
                      ((Groupproject) collGroupprojects.get(i))
                          .setProjectid(v);
                  }
              }
                                   }


        /**
         * Get the Name
         *
         * @return String
         */
        public String getName()
        {
            return name;
        }

                                            
        /**
         * Set the value of Name
         *
         * @param v new value
         */
        public void setName(String v) 
        {
          


         if (!ObjectUtils.equals(this.name, v))
        {
             this.name = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Startdate
         *
         * @return Date
         */
        public Date getStartdate()
        {
            return startdate;
        }

                                            
        /**
         * Set the value of Startdate
         *
         * @param v new value
         */
        public void setStartdate(Date v) 
        {
          


         if (!ObjectUtils.equals(this.startdate, v))
        {
             this.startdate = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Created
         *
         * @return Date
         */
        public Date getCreated()
        {
            return created;
        }

                                            
        /**
         * Set the value of Created
         *
         * @param v new value
         */
        public void setCreated(Date v) 
        {
          


         if (!ObjectUtils.equals(this.created, v))
        {
             this.created = v;
            setModified(true);
        }

                  
                       }


 
        
                
      
    /**
     * Collection to store aggregation of collTasks
     */
    protected List collTasks;

    /**
     * Temporary storage of collTasks to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initTasks()
    {
        if (collTasks == null)
        {
            collTasks = new ArrayList();
        }
    }

    /**
     * Method called to associate a Task object to this object
     * through the Task foreign key attribute
     *
     * @param l Task
     * @throws TorqueException
     */
    public void addTask(Task l) throws TorqueException
    {
        getTasks().add(l);
        l.setProject((Project) this);
    }

    /**
     * The criteria used to select the current contents of collTasks
     */
    private Criteria lastTasksCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getTasks(new Criteria())
     *
     * @throws TorqueException
     */
    public List getTasks() throws TorqueException
    {
        if (collTasks == null)
        {
            collTasks = getTasks(new Criteria(10));
        }
        return collTasks;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project has previously
     * been saved, it will retrieve related Tasks from storage.
     * If this Project is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getTasks(Criteria criteria) throws TorqueException
    {
        if (collTasks == null)
        {
            if (isNew())
            {
               collTasks = new ArrayList();
            }
            else
            {
                   criteria.add(TaskPeer.PROJECTID, getProjectid() );
                   collTasks = TaskPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(TaskPeer.PROJECTID, getProjectid());
                   if (!lastTasksCriteria.equals(criteria))
                {
                    collTasks = TaskPeer.doSelect(criteria);
                }
            }
        }
        lastTasksCriteria = criteria;

        return collTasks;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getTasks(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getTasks(Connection con) throws TorqueException
    {
        if (collTasks == null)
        {
            collTasks = getTasks(new Criteria(10), con);
        }
        return collTasks;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project has previously
     * been saved, it will retrieve related Tasks from storage.
     * If this Project is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getTasks(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collTasks == null)
        {
            if (isNew())
            {
               collTasks = new ArrayList();
            }
            else
            {
                     criteria.add(TaskPeer.PROJECTID, getProjectid());
                     collTasks = TaskPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(TaskPeer.PROJECTID, getProjectid());
                     if (!lastTasksCriteria.equals(criteria))
                 {
                     collTasks = TaskPeer.doSelect(criteria, con);
                 }
             }
         }
         lastTasksCriteria = criteria;

         return collTasks;
     }

        

     
      
         
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project is new, it will return
     * an empty collection; or if this Project has previously
     * been saved, it will retrieve related Tasks from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Project.
     */
    protected List getTasksJoinProject(Criteria criteria)
        throws TorqueException
    {
        if (collTasks == null)
        {
            if (isNew())
            {
               collTasks = new ArrayList();
            }
            else
            {
                   criteria.add(TaskPeer.PROJECTID, getProjectid());
                   collTasks = TaskPeer.doSelectJoinProject(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskPeer.PROJECTID, getProjectid());
               if (!lastTasksCriteria.equals(criteria))
            {
                collTasks = TaskPeer.doSelectJoinProject(criteria);
            }
        }
        lastTasksCriteria = criteria;

        return collTasks;
    }
   
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project is new, it will return
     * an empty collection; or if this Project has previously
     * been saved, it will retrieve related Tasks from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Project.
     */
    protected List getTasksJoinLkptype(Criteria criteria)
        throws TorqueException
    {
        if (collTasks == null)
        {
            if (isNew())
            {
               collTasks = new ArrayList();
            }
            else
            {
                   criteria.add(TaskPeer.PROJECTID, getProjectid());
                   collTasks = TaskPeer.doSelectJoinLkptype(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskPeer.PROJECTID, getProjectid());
               if (!lastTasksCriteria.equals(criteria))
            {
                collTasks = TaskPeer.doSelectJoinLkptype(criteria);
            }
        }
        lastTasksCriteria = criteria;

        return collTasks;
    }
   
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project is new, it will return
     * an empty collection; or if this Project has previously
     * been saved, it will retrieve related Tasks from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Project.
     */
    protected List getTasksJoinLkpstatus(Criteria criteria)
        throws TorqueException
    {
        if (collTasks == null)
        {
            if (isNew())
            {
               collTasks = new ArrayList();
            }
            else
            {
                   criteria.add(TaskPeer.PROJECTID, getProjectid());
                   collTasks = TaskPeer.doSelectJoinLkpstatus(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskPeer.PROJECTID, getProjectid());
               if (!lastTasksCriteria.equals(criteria))
            {
                collTasks = TaskPeer.doSelectJoinLkpstatus(criteria);
            }
        }
        lastTasksCriteria = criteria;

        return collTasks;
    }
   
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project is new, it will return
     * an empty collection; or if this Project has previously
     * been saved, it will retrieve related Tasks from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Project.
     */
    protected List getTasksJoinLkppriority(Criteria criteria)
        throws TorqueException
    {
        if (collTasks == null)
        {
            if (isNew())
            {
               collTasks = new ArrayList();
            }
            else
            {
                   criteria.add(TaskPeer.PROJECTID, getProjectid());
                   collTasks = TaskPeer.doSelectJoinLkppriority(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskPeer.PROJECTID, getProjectid());
               if (!lastTasksCriteria.equals(criteria))
            {
                collTasks = TaskPeer.doSelectJoinLkppriority(criteria);
            }
        }
        lastTasksCriteria = criteria;

        return collTasks;
    }
   
      
      
              
                                    
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project is new, it will return
     * an empty collection; or if this Project has previously
     * been saved, it will retrieve related Tasks from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Project.
     */
    protected List getTasksJoinUsersRelatedByOwnerid(Criteria criteria)
        throws TorqueException
    {
        if (collTasks == null)
        {
            if (isNew())
            {
               collTasks = new ArrayList();
            }
            else
            {
                   criteria.add(TaskPeer.PROJECTID, getProjectid());
                   collTasks = TaskPeer.doSelectJoinUsersRelatedByOwnerid(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskPeer.PROJECTID, getProjectid());
               if (!lastTasksCriteria.equals(criteria))
            {
                collTasks = TaskPeer.doSelectJoinUsersRelatedByOwnerid(criteria);
            }
        }
        lastTasksCriteria = criteria;

        return collTasks;
    }
   
      
      
              
                                    
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project is new, it will return
     * an empty collection; or if this Project has previously
     * been saved, it will retrieve related Tasks from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Project.
     */
    protected List getTasksJoinUsersRelatedByAssigned(Criteria criteria)
        throws TorqueException
    {
        if (collTasks == null)
        {
            if (isNew())
            {
               collTasks = new ArrayList();
            }
            else
            {
                   criteria.add(TaskPeer.PROJECTID, getProjectid());
                   collTasks = TaskPeer.doSelectJoinUsersRelatedByAssigned(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskPeer.PROJECTID, getProjectid());
               if (!lastTasksCriteria.equals(criteria))
            {
                collTasks = TaskPeer.doSelectJoinUsersRelatedByAssigned(criteria);
            }
        }
        lastTasksCriteria = criteria;

        return collTasks;
    }
     



             
      
    /**
     * Collection to store aggregation of collTodos
     */
    protected List collTodos;

    /**
     * Temporary storage of collTodos to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initTodos()
    {
        if (collTodos == null)
        {
            collTodos = new ArrayList();
        }
    }

    /**
     * Method called to associate a Todo object to this object
     * through the Todo foreign key attribute
     *
     * @param l Todo
     * @throws TorqueException
     */
    public void addTodo(Todo l) throws TorqueException
    {
        getTodos().add(l);
        l.setProject((Project) this);
    }

    /**
     * The criteria used to select the current contents of collTodos
     */
    private Criteria lastTodosCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getTodos(new Criteria())
     *
     * @throws TorqueException
     */
    public List getTodos() throws TorqueException
    {
        if (collTodos == null)
        {
            collTodos = getTodos(new Criteria(10));
        }
        return collTodos;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project has previously
     * been saved, it will retrieve related Todos from storage.
     * If this Project is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getTodos(Criteria criteria) throws TorqueException
    {
        if (collTodos == null)
        {
            if (isNew())
            {
               collTodos = new ArrayList();
            }
            else
            {
                   criteria.add(TodoPeer.PROJECTID, getProjectid() );
                   collTodos = TodoPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(TodoPeer.PROJECTID, getProjectid());
                   if (!lastTodosCriteria.equals(criteria))
                {
                    collTodos = TodoPeer.doSelect(criteria);
                }
            }
        }
        lastTodosCriteria = criteria;

        return collTodos;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getTodos(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getTodos(Connection con) throws TorqueException
    {
        if (collTodos == null)
        {
            collTodos = getTodos(new Criteria(10), con);
        }
        return collTodos;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project has previously
     * been saved, it will retrieve related Todos from storage.
     * If this Project is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getTodos(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collTodos == null)
        {
            if (isNew())
            {
               collTodos = new ArrayList();
            }
            else
            {
                     criteria.add(TodoPeer.PROJECTID, getProjectid());
                     collTodos = TodoPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(TodoPeer.PROJECTID, getProjectid());
                     if (!lastTodosCriteria.equals(criteria))
                 {
                     collTodos = TodoPeer.doSelect(criteria, con);
                 }
             }
         }
         lastTodosCriteria = criteria;

         return collTodos;
     }

      

     
      
         
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project is new, it will return
     * an empty collection; or if this Project has previously
     * been saved, it will retrieve related Todos from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Project.
     */
    protected List getTodosJoinProject(Criteria criteria)
        throws TorqueException
    {
        if (collTodos == null)
        {
            if (isNew())
            {
               collTodos = new ArrayList();
            }
            else
            {
                   criteria.add(TodoPeer.PROJECTID, getProjectid());
                   collTodos = TodoPeer.doSelectJoinProject(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TodoPeer.PROJECTID, getProjectid());
               if (!lastTodosCriteria.equals(criteria))
            {
                collTodos = TodoPeer.doSelectJoinProject(criteria);
            }
        }
        lastTodosCriteria = criteria;

        return collTodos;
    }
   
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project is new, it will return
     * an empty collection; or if this Project has previously
     * been saved, it will retrieve related Todos from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Project.
     */
    protected List getTodosJoinLkptype(Criteria criteria)
        throws TorqueException
    {
        if (collTodos == null)
        {
            if (isNew())
            {
               collTodos = new ArrayList();
            }
            else
            {
                   criteria.add(TodoPeer.PROJECTID, getProjectid());
                   collTodos = TodoPeer.doSelectJoinLkptype(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TodoPeer.PROJECTID, getProjectid());
               if (!lastTodosCriteria.equals(criteria))
            {
                collTodos = TodoPeer.doSelectJoinLkptype(criteria);
            }
        }
        lastTodosCriteria = criteria;

        return collTodos;
    }
   
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project is new, it will return
     * an empty collection; or if this Project has previously
     * been saved, it will retrieve related Todos from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Project.
     */
    protected List getTodosJoinLkpstatus(Criteria criteria)
        throws TorqueException
    {
        if (collTodos == null)
        {
            if (isNew())
            {
               collTodos = new ArrayList();
            }
            else
            {
                   criteria.add(TodoPeer.PROJECTID, getProjectid());
                   collTodos = TodoPeer.doSelectJoinLkpstatus(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TodoPeer.PROJECTID, getProjectid());
               if (!lastTodosCriteria.equals(criteria))
            {
                collTodos = TodoPeer.doSelectJoinLkpstatus(criteria);
            }
        }
        lastTodosCriteria = criteria;

        return collTodos;
    }
   
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project is new, it will return
     * an empty collection; or if this Project has previously
     * been saved, it will retrieve related Todos from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Project.
     */
    protected List getTodosJoinLkppriority(Criteria criteria)
        throws TorqueException
    {
        if (collTodos == null)
        {
            if (isNew())
            {
               collTodos = new ArrayList();
            }
            else
            {
                   criteria.add(TodoPeer.PROJECTID, getProjectid());
                   collTodos = TodoPeer.doSelectJoinLkppriority(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TodoPeer.PROJECTID, getProjectid());
               if (!lastTodosCriteria.equals(criteria))
            {
                collTodos = TodoPeer.doSelectJoinLkppriority(criteria);
            }
        }
        lastTodosCriteria = criteria;

        return collTodos;
    }
     



             
      
    /**
     * Collection to store aggregation of collUserprojects
     */
    protected List collUserprojects;

    /**
     * Temporary storage of collUserprojects to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initUserprojects()
    {
        if (collUserprojects == null)
        {
            collUserprojects = new ArrayList();
        }
    }

    /**
     * Method called to associate a Userproject object to this object
     * through the Userproject foreign key attribute
     *
     * @param l Userproject
     * @throws TorqueException
     */
    public void addUserproject(Userproject l) throws TorqueException
    {
        getUserprojects().add(l);
        l.setProject((Project) this);
    }

    /**
     * The criteria used to select the current contents of collUserprojects
     */
    private Criteria lastUserprojectsCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getUserprojects(new Criteria())
     *
     * @throws TorqueException
     */
    public List getUserprojects() throws TorqueException
    {
        if (collUserprojects == null)
        {
            collUserprojects = getUserprojects(new Criteria(10));
        }
        return collUserprojects;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project has previously
     * been saved, it will retrieve related Userprojects from storage.
     * If this Project is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getUserprojects(Criteria criteria) throws TorqueException
    {
        if (collUserprojects == null)
        {
            if (isNew())
            {
               collUserprojects = new ArrayList();
            }
            else
            {
                   criteria.add(UserprojectPeer.PROJECTID, getProjectid() );
                   collUserprojects = UserprojectPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(UserprojectPeer.PROJECTID, getProjectid());
                   if (!lastUserprojectsCriteria.equals(criteria))
                {
                    collUserprojects = UserprojectPeer.doSelect(criteria);
                }
            }
        }
        lastUserprojectsCriteria = criteria;

        return collUserprojects;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getUserprojects(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getUserprojects(Connection con) throws TorqueException
    {
        if (collUserprojects == null)
        {
            collUserprojects = getUserprojects(new Criteria(10), con);
        }
        return collUserprojects;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project has previously
     * been saved, it will retrieve related Userprojects from storage.
     * If this Project is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getUserprojects(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collUserprojects == null)
        {
            if (isNew())
            {
               collUserprojects = new ArrayList();
            }
            else
            {
                     criteria.add(UserprojectPeer.PROJECTID, getProjectid());
                     collUserprojects = UserprojectPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(UserprojectPeer.PROJECTID, getProjectid());
                     if (!lastUserprojectsCriteria.equals(criteria))
                 {
                     collUserprojects = UserprojectPeer.doSelect(criteria, con);
                 }
             }
         }
         lastUserprojectsCriteria = criteria;

         return collUserprojects;
     }

    

     
      
         
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project is new, it will return
     * an empty collection; or if this Project has previously
     * been saved, it will retrieve related Userprojects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Project.
     */
    protected List getUserprojectsJoinProject(Criteria criteria)
        throws TorqueException
    {
        if (collUserprojects == null)
        {
            if (isNew())
            {
               collUserprojects = new ArrayList();
            }
            else
            {
                   criteria.add(UserprojectPeer.PROJECTID, getProjectid());
                   collUserprojects = UserprojectPeer.doSelectJoinProject(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(UserprojectPeer.PROJECTID, getProjectid());
               if (!lastUserprojectsCriteria.equals(criteria))
            {
                collUserprojects = UserprojectPeer.doSelectJoinProject(criteria);
            }
        }
        lastUserprojectsCriteria = criteria;

        return collUserprojects;
    }
   
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project is new, it will return
     * an empty collection; or if this Project has previously
     * been saved, it will retrieve related Userprojects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Project.
     */
    protected List getUserprojectsJoinUsers(Criteria criteria)
        throws TorqueException
    {
        if (collUserprojects == null)
        {
            if (isNew())
            {
               collUserprojects = new ArrayList();
            }
            else
            {
                   criteria.add(UserprojectPeer.PROJECTID, getProjectid());
                   collUserprojects = UserprojectPeer.doSelectJoinUsers(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(UserprojectPeer.PROJECTID, getProjectid());
               if (!lastUserprojectsCriteria.equals(criteria))
            {
                collUserprojects = UserprojectPeer.doSelectJoinUsers(criteria);
            }
        }
        lastUserprojectsCriteria = criteria;

        return collUserprojects;
    }
     



             
      
    /**
     * Collection to store aggregation of collGroupprojects
     */
    protected List collGroupprojects;

    /**
     * Temporary storage of collGroupprojects to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initGroupprojects()
    {
        if (collGroupprojects == null)
        {
            collGroupprojects = new ArrayList();
        }
    }

    /**
     * Method called to associate a Groupproject object to this object
     * through the Groupproject foreign key attribute
     *
     * @param l Groupproject
     * @throws TorqueException
     */
    public void addGroupproject(Groupproject l) throws TorqueException
    {
        getGroupprojects().add(l);
        l.setProject((Project) this);
    }

    /**
     * The criteria used to select the current contents of collGroupprojects
     */
    private Criteria lastGroupprojectsCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getGroupprojects(new Criteria())
     *
     * @throws TorqueException
     */
    public List getGroupprojects() throws TorqueException
    {
        if (collGroupprojects == null)
        {
            collGroupprojects = getGroupprojects(new Criteria(10));
        }
        return collGroupprojects;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project has previously
     * been saved, it will retrieve related Groupprojects from storage.
     * If this Project is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getGroupprojects(Criteria criteria) throws TorqueException
    {
        if (collGroupprojects == null)
        {
            if (isNew())
            {
               collGroupprojects = new ArrayList();
            }
            else
            {
                   criteria.add(GroupprojectPeer.PROJECTID, getProjectid() );
                   collGroupprojects = GroupprojectPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(GroupprojectPeer.PROJECTID, getProjectid());
                   if (!lastGroupprojectsCriteria.equals(criteria))
                {
                    collGroupprojects = GroupprojectPeer.doSelect(criteria);
                }
            }
        }
        lastGroupprojectsCriteria = criteria;

        return collGroupprojects;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getGroupprojects(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getGroupprojects(Connection con) throws TorqueException
    {
        if (collGroupprojects == null)
        {
            collGroupprojects = getGroupprojects(new Criteria(10), con);
        }
        return collGroupprojects;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project has previously
     * been saved, it will retrieve related Groupprojects from storage.
     * If this Project is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getGroupprojects(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collGroupprojects == null)
        {
            if (isNew())
            {
               collGroupprojects = new ArrayList();
            }
            else
            {
                     criteria.add(GroupprojectPeer.PROJECTID, getProjectid());
                     collGroupprojects = GroupprojectPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(GroupprojectPeer.PROJECTID, getProjectid());
                     if (!lastGroupprojectsCriteria.equals(criteria))
                 {
                     collGroupprojects = GroupprojectPeer.doSelect(criteria, con);
                 }
             }
         }
         lastGroupprojectsCriteria = criteria;

         return collGroupprojects;
     }

    

     
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project is new, it will return
     * an empty collection; or if this Project has previously
     * been saved, it will retrieve related Groupprojects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Project.
     */
    protected List getGroupprojectsJoinGroups(Criteria criteria)
        throws TorqueException
    {
        if (collGroupprojects == null)
        {
            if (isNew())
            {
               collGroupprojects = new ArrayList();
            }
            else
            {
                   criteria.add(GroupprojectPeer.PROJECTID, getProjectid());
                   collGroupprojects = GroupprojectPeer.doSelectJoinGroups(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(GroupprojectPeer.PROJECTID, getProjectid());
               if (!lastGroupprojectsCriteria.equals(criteria))
            {
                collGroupprojects = GroupprojectPeer.doSelectJoinGroups(criteria);
            }
        }
        lastGroupprojectsCriteria = criteria;

        return collGroupprojects;
    }
   
      
         
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Project is new, it will return
     * an empty collection; or if this Project has previously
     * been saved, it will retrieve related Groupprojects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Project.
     */
    protected List getGroupprojectsJoinProject(Criteria criteria)
        throws TorqueException
    {
        if (collGroupprojects == null)
        {
            if (isNew())
            {
               collGroupprojects = new ArrayList();
            }
            else
            {
                   criteria.add(GroupprojectPeer.PROJECTID, getProjectid());
                   collGroupprojects = GroupprojectPeer.doSelectJoinProject(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(GroupprojectPeer.PROJECTID, getProjectid());
               if (!lastGroupprojectsCriteria.equals(criteria))
            {
                collGroupprojects = GroupprojectPeer.doSelectJoinProject(criteria);
            }
        }
        lastGroupprojectsCriteria = criteria;

        return collGroupprojects;
    }
     



     
    
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
      if (fieldNames == null)
      {
        fieldNames = new ArrayList();
            fieldNames.add("Projectid");
            fieldNames.add("Name");
            fieldNames.add("Startdate");
            fieldNames.add("Created");
            fieldNames = Collections.unmodifiableList(fieldNames);
      }
      return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
            if (name.equals("Projectid"))
    {
              return new Integer(getProjectid());
          }
            if (name.equals("Name"))
    {
              return getName();
          }
            if (name.equals("Startdate"))
    {
              return getStartdate();
          }
            if (name.equals("Created"))
    {
              return getCreated();
          }
            return null;
    }
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
            if (name.equals(ProjectPeer.PROJECTID))
        {
              return new Integer(getProjectid());
          }
            if (name.equals(ProjectPeer.NAME))
        {
              return getName();
          }
            if (name.equals(ProjectPeer.STARTDATE))
        {
              return getStartdate();
          }
            if (name.equals(ProjectPeer.CREATED))
        {
              return getCreated();
          }
            return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
    {
              return new Integer(getProjectid());
          }
            if (pos == 1)
    {
              return getName();
          }
            if (pos == 2)
    {
              return getStartdate();
          }
            if (pos == 3)
    {
              return getCreated();
          }
                return null;
    }

     


    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
             save(ProjectPeer.getMapBuilder()
                .getDatabaseMap().getName());
     }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
         try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }

     }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;



  
        // If this object has been modified, then save it to the database.
        if (isModified())
        {
            if (isNew())
            {
                ProjectPeer.doInsert((Project) this, con);
                setNew(false);
            }
            else
            {
                ProjectPeer.doUpdate((Project) this, con);
            }
        }

                                    
                
          if (collTasks != null)
          {
              for (int i = 0; i < collTasks.size(); i++)
              {
                  ((Task) collTasks.get(i)).save(con);
              }
          }
                                        
                
          if (collTodos != null)
          {
              for (int i = 0; i < collTodos.size(); i++)
              {
                  ((Todo) collTodos.get(i)).save(con);
              }
          }
                                        
                
          if (collUserprojects != null)
          {
              for (int i = 0; i < collUserprojects.size(); i++)
              {
                  ((Userproject) collUserprojects.get(i)).save(con);
              }
          }
                                        
                
          if (collGroupprojects != null)
          {
              for (int i = 0; i < collGroupprojects.size(); i++)
              {
                  ((Groupproject) collGroupprojects.get(i)).save(con);
              }
          }
                  alreadyInSave = false;
      }
      }


                        
    
    

        /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  projectid ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
                    setProjectid(((NumberKey) key).intValue());
            }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
                    setProjectid(Integer.parseInt(key));
            }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getProjectid());
    }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Project copy() throws TorqueException
    {
        return copyInto(new Project());
    }

    protected Project copyInto(Project copyObj) throws TorqueException
    {
        copyObj.setProjectid(projectid);
        copyObj.setName(name);
        copyObj.setStartdate(startdate);
        copyObj.setCreated(created);

                      copyObj.setProjectid(0);
                        

                                  
                
        List v = getTasks();
        for (int i = 0; i < v.size(); i++)
        {
            Task obj = (Task) v.get(i);
            copyObj.addTask(obj.copy());
        }
                                              
                
        v = getTodos();
        for (int i = 0; i < v.size(); i++)
        {
            Todo obj = (Todo) v.get(i);
            copyObj.addTodo(obj.copy());
        }
                                              
                
        v = getUserprojects();
        for (int i = 0; i < v.size(); i++)
        {
            Userproject obj = (Userproject) v.get(i);
            copyObj.addUserproject(obj.copy());
        }
                                              
                
        v = getGroupprojects();
        for (int i = 0; i < v.size(); i++)
        {
            Groupproject obj = (Groupproject) v.get(i);
            copyObj.addGroupproject(obj.copy());
        }
              
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public ProjectPeer getPeer()
    {
        return peer;
    }
}
