package com.sns.scout.managers;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;

   
      
   
/**
 * This class was autogenerated by Torque on:
 *
 * [Tue Jan 19 16:39:36 CST 2010]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Usergroup
 */
public abstract class BaseUsergroup extends BaseObject
{
    /** The Peer class */
    private static final UsergroupPeer peer =
        new UsergroupPeer();

                  
        /**
         * The value for the userid field
         */
        private int userid;
              
        /**
         * The value for the groupid field
         */
        private int groupid;
      
      
        /**
         * Get the Userid
         *
         * @return int
         */
        public int getUserid()
        {
            return userid;
        }

                                                      
        /**
         * Set the value of Userid
         *
         * @param v new value
         */
        public void setUserid(int v) throws TorqueException
        {
          


         if (this.userid != v)
        {
             this.userid = v;
            setModified(true);
        }

                                          
                if (aUsers != null && !(aUsers.getUserid()==v))
                {
            aUsers = null;
        }
          
                       }


        /**
         * Get the Groupid
         *
         * @return int
         */
        public int getGroupid()
        {
            return groupid;
        }

                                                      
        /**
         * Set the value of Groupid
         *
         * @param v new value
         */
        public void setGroupid(int v) throws TorqueException
        {
          


         if (this.groupid != v)
        {
             this.groupid = v;
            setModified(true);
        }

                                          
                if (aGroups != null && !(aGroups.getGroupid()==v))
                {
            aGroups = null;
        }
          
                       }


 
     
   
             
   
       private Groups aGroups;

    /**
     * Declares an association between this object and a Groups object
     *
     * @param v Groups
     * @throws TorqueException
     */
    public void setGroups(Groups v) throws TorqueException
    {
           if (v == null)
        {
                        setGroupid(0);
                    }
        else
        {
            setGroupid(v.getGroupid());
        }
           aGroups = v;
    }

                 
    /**
     * Get the associated Groups object
     *
     * @return the associated Groups object
     * @throws TorqueException
     */
    public Groups getGroups() throws TorqueException
    {
        if (aGroups == null && (this.groupid > 0))
        {
              aGroups = GroupsPeer.retrieveByPK(SimpleKey.keyFor(this.groupid));
      
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               Groups obj = GroupsPeer.retrieveByPK(this.groupid);
               obj.addUsergroups(this);
             */
        }
        return aGroups;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setGroupsKey(ObjectKey key) throws TorqueException
    {
    
                                        setGroupid(((NumberKey) key).intValue());
                    }
 
   
             
   
       private Users aUsers;

    /**
     * Declares an association between this object and a Users object
     *
     * @param v Users
     * @throws TorqueException
     */
    public void setUsers(Users v) throws TorqueException
    {
           if (v == null)
        {
                        setUserid(0);
                    }
        else
        {
            setUserid(v.getUserid());
        }
           aUsers = v;
    }

                 
    /**
     * Get the associated Users object
     *
     * @return the associated Users object
     * @throws TorqueException
     */
    public Users getUsers() throws TorqueException
    {
        if (aUsers == null && (this.userid > 0))
        {
              aUsers = UsersPeer.retrieveByPK(SimpleKey.keyFor(this.userid));
      
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               Users obj = UsersPeer.retrieveByPK(this.userid);
               obj.addUsergroups(this);
             */
        }
        return aUsers;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setUsersKey(ObjectKey key) throws TorqueException
    {
    
                                        setUserid(((NumberKey) key).intValue());
                    }
    
        
    
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
      if (fieldNames == null)
      {
        fieldNames = new ArrayList();
            fieldNames.add("Userid");
            fieldNames.add("Groupid");
            fieldNames = Collections.unmodifiableList(fieldNames);
      }
      return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
            if (name.equals("Userid"))
    {
              return new Integer(getUserid());
          }
            if (name.equals("Groupid"))
    {
              return new Integer(getGroupid());
          }
            return null;
    }
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
            if (name.equals(UsergroupPeer.USERID))
        {
              return new Integer(getUserid());
          }
            if (name.equals(UsergroupPeer.GROUPID))
        {
              return new Integer(getGroupid());
          }
            return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
    {
              return new Integer(getUserid());
          }
            if (pos == 1)
    {
              return new Integer(getGroupid());
          }
                return null;
    }

     


    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
             save(UsergroupPeer.getMapBuilder()
                .getDatabaseMap().getName());
     }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
         try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }

     }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;



  
        // If this object has been modified, then save it to the database.
        if (isModified())
        {
            if (isNew())
            {
                UsergroupPeer.doInsert((Usergroup) this, con);
                setNew(false);
            }
            else
            {
                UsergroupPeer.doUpdate((Usergroup) this, con);
            }
        }

              alreadyInSave = false;
      }
      }




    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return null;
    }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Usergroup copy() throws TorqueException
    {
        return copyInto(new Usergroup());
    }

    protected Usergroup copyInto(Usergroup copyObj) throws TorqueException
    {
        copyObj.setUserid(userid);
        copyObj.setGroupid(groupid);

        

  
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public UsergroupPeer getPeer()
    {
        return peer;
    }
}
