package com.sns.scout.managers;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;


/**
 * This class was autogenerated by Torque on:
 *
 * [Tue Jan 19 16:39:36 CST 2010]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Lkppriority
 */
public abstract class BaseLkppriority extends BaseObject
{
    /** The Peer class */
    private static final LkppriorityPeer peer =
        new LkppriorityPeer();

                  
        /**
         * The value for the priorityid field
         */
        private int priorityid;
                                                                                      
        /**
         * The value for the name field
         */
        private String name = "";
                                                                                      
        /**
         * The value for the description field
         */
        private String description = "";
      
      
        /**
         * Get the Priorityid
         *
         * @return int
         */
        public int getPriorityid()
        {
            return priorityid;
        }

                                                                              
        /**
         * Set the value of Priorityid
         *
         * @param v new value
         */
        public void setPriorityid(int v) throws TorqueException
        {
          


         if (this.priorityid != v)
        {
             this.priorityid = v;
            setModified(true);
        }

                  
                                                  
              // update associated Task
              if (collTasks != null)
              {
                  for (int i = 0; i < collTasks.size(); i++)
                  {
                      ((Task) collTasks.get(i))
                          .setPriorityid(v);
                  }
              }
                                                              
              // update associated Todo
              if (collTodos != null)
              {
                  for (int i = 0; i < collTodos.size(); i++)
                  {
                      ((Todo) collTodos.get(i))
                          .setPriorityid(v);
                  }
              }
                                                              
              // update associated Taskestimate
              if (collTaskestimates != null)
              {
                  for (int i = 0; i < collTaskestimates.size(); i++)
                  {
                      ((Taskestimate) collTaskestimates.get(i))
                          .setPriorityid(v);
                  }
              }
                                                              
              // update associated Taskactual
              if (collTaskactuals != null)
              {
                  for (int i = 0; i < collTaskactuals.size(); i++)
                  {
                      ((Taskactual) collTaskactuals.get(i))
                          .setPriorityid(v);
                  }
              }
                                   }


        /**
         * Get the Name
         *
         * @return String
         */
        public String getName()
        {
            return name;
        }

                                            
        /**
         * Set the value of Name
         *
         * @param v new value
         */
        public void setName(String v) 
        {
          


         if (!ObjectUtils.equals(this.name, v))
        {
             this.name = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Description
         *
         * @return String
         */
        public String getDescription()
        {
            return description;
        }

                                            
        /**
         * Set the value of Description
         *
         * @param v new value
         */
        public void setDescription(String v) 
        {
          


         if (!ObjectUtils.equals(this.description, v))
        {
             this.description = v;
            setModified(true);
        }

                  
                       }


 
        
                
      
    /**
     * Collection to store aggregation of collTasks
     */
    protected List collTasks;

    /**
     * Temporary storage of collTasks to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initTasks()
    {
        if (collTasks == null)
        {
            collTasks = new ArrayList();
        }
    }

    /**
     * Method called to associate a Task object to this object
     * through the Task foreign key attribute
     *
     * @param l Task
     * @throws TorqueException
     */
    public void addTask(Task l) throws TorqueException
    {
        getTasks().add(l);
        l.setLkppriority((Lkppriority) this);
    }

    /**
     * The criteria used to select the current contents of collTasks
     */
    private Criteria lastTasksCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getTasks(new Criteria())
     *
     * @throws TorqueException
     */
    public List getTasks() throws TorqueException
    {
        if (collTasks == null)
        {
            collTasks = getTasks(new Criteria(10));
        }
        return collTasks;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority has previously
     * been saved, it will retrieve related Tasks from storage.
     * If this Lkppriority is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getTasks(Criteria criteria) throws TorqueException
    {
        if (collTasks == null)
        {
            if (isNew())
            {
               collTasks = new ArrayList();
            }
            else
            {
                   criteria.add(TaskPeer.PRIORITYID, getPriorityid() );
                   collTasks = TaskPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(TaskPeer.PRIORITYID, getPriorityid());
                   if (!lastTasksCriteria.equals(criteria))
                {
                    collTasks = TaskPeer.doSelect(criteria);
                }
            }
        }
        lastTasksCriteria = criteria;

        return collTasks;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getTasks(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getTasks(Connection con) throws TorqueException
    {
        if (collTasks == null)
        {
            collTasks = getTasks(new Criteria(10), con);
        }
        return collTasks;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority has previously
     * been saved, it will retrieve related Tasks from storage.
     * If this Lkppriority is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getTasks(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collTasks == null)
        {
            if (isNew())
            {
               collTasks = new ArrayList();
            }
            else
            {
                     criteria.add(TaskPeer.PRIORITYID, getPriorityid());
                     collTasks = TaskPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(TaskPeer.PRIORITYID, getPriorityid());
                     if (!lastTasksCriteria.equals(criteria))
                 {
                     collTasks = TaskPeer.doSelect(criteria, con);
                 }
             }
         }
         lastTasksCriteria = criteria;

         return collTasks;
     }

        

     
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority is new, it will return
     * an empty collection; or if this Lkppriority has previously
     * been saved, it will retrieve related Tasks from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Lkppriority.
     */
    protected List getTasksJoinProject(Criteria criteria)
        throws TorqueException
    {
        if (collTasks == null)
        {
            if (isNew())
            {
               collTasks = new ArrayList();
            }
            else
            {
                   criteria.add(TaskPeer.PRIORITYID, getPriorityid());
                   collTasks = TaskPeer.doSelectJoinProject(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskPeer.PRIORITYID, getPriorityid());
               if (!lastTasksCriteria.equals(criteria))
            {
                collTasks = TaskPeer.doSelectJoinProject(criteria);
            }
        }
        lastTasksCriteria = criteria;

        return collTasks;
    }
   
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority is new, it will return
     * an empty collection; or if this Lkppriority has previously
     * been saved, it will retrieve related Tasks from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Lkppriority.
     */
    protected List getTasksJoinLkptype(Criteria criteria)
        throws TorqueException
    {
        if (collTasks == null)
        {
            if (isNew())
            {
               collTasks = new ArrayList();
            }
            else
            {
                   criteria.add(TaskPeer.PRIORITYID, getPriorityid());
                   collTasks = TaskPeer.doSelectJoinLkptype(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskPeer.PRIORITYID, getPriorityid());
               if (!lastTasksCriteria.equals(criteria))
            {
                collTasks = TaskPeer.doSelectJoinLkptype(criteria);
            }
        }
        lastTasksCriteria = criteria;

        return collTasks;
    }
   
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority is new, it will return
     * an empty collection; or if this Lkppriority has previously
     * been saved, it will retrieve related Tasks from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Lkppriority.
     */
    protected List getTasksJoinLkpstatus(Criteria criteria)
        throws TorqueException
    {
        if (collTasks == null)
        {
            if (isNew())
            {
               collTasks = new ArrayList();
            }
            else
            {
                   criteria.add(TaskPeer.PRIORITYID, getPriorityid());
                   collTasks = TaskPeer.doSelectJoinLkpstatus(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskPeer.PRIORITYID, getPriorityid());
               if (!lastTasksCriteria.equals(criteria))
            {
                collTasks = TaskPeer.doSelectJoinLkpstatus(criteria);
            }
        }
        lastTasksCriteria = criteria;

        return collTasks;
    }
   
      
         
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority is new, it will return
     * an empty collection; or if this Lkppriority has previously
     * been saved, it will retrieve related Tasks from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Lkppriority.
     */
    protected List getTasksJoinLkppriority(Criteria criteria)
        throws TorqueException
    {
        if (collTasks == null)
        {
            if (isNew())
            {
               collTasks = new ArrayList();
            }
            else
            {
                   criteria.add(TaskPeer.PRIORITYID, getPriorityid());
                   collTasks = TaskPeer.doSelectJoinLkppriority(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskPeer.PRIORITYID, getPriorityid());
               if (!lastTasksCriteria.equals(criteria))
            {
                collTasks = TaskPeer.doSelectJoinLkppriority(criteria);
            }
        }
        lastTasksCriteria = criteria;

        return collTasks;
    }
   
      
      
              
                                    
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority is new, it will return
     * an empty collection; or if this Lkppriority has previously
     * been saved, it will retrieve related Tasks from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Lkppriority.
     */
    protected List getTasksJoinUsersRelatedByOwnerid(Criteria criteria)
        throws TorqueException
    {
        if (collTasks == null)
        {
            if (isNew())
            {
               collTasks = new ArrayList();
            }
            else
            {
                   criteria.add(TaskPeer.PRIORITYID, getPriorityid());
                   collTasks = TaskPeer.doSelectJoinUsersRelatedByOwnerid(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskPeer.PRIORITYID, getPriorityid());
               if (!lastTasksCriteria.equals(criteria))
            {
                collTasks = TaskPeer.doSelectJoinUsersRelatedByOwnerid(criteria);
            }
        }
        lastTasksCriteria = criteria;

        return collTasks;
    }
   
      
      
              
                                    
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority is new, it will return
     * an empty collection; or if this Lkppriority has previously
     * been saved, it will retrieve related Tasks from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Lkppriority.
     */
    protected List getTasksJoinUsersRelatedByAssigned(Criteria criteria)
        throws TorqueException
    {
        if (collTasks == null)
        {
            if (isNew())
            {
               collTasks = new ArrayList();
            }
            else
            {
                   criteria.add(TaskPeer.PRIORITYID, getPriorityid());
                   collTasks = TaskPeer.doSelectJoinUsersRelatedByAssigned(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskPeer.PRIORITYID, getPriorityid());
               if (!lastTasksCriteria.equals(criteria))
            {
                collTasks = TaskPeer.doSelectJoinUsersRelatedByAssigned(criteria);
            }
        }
        lastTasksCriteria = criteria;

        return collTasks;
    }
     



             
      
    /**
     * Collection to store aggregation of collTodos
     */
    protected List collTodos;

    /**
     * Temporary storage of collTodos to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initTodos()
    {
        if (collTodos == null)
        {
            collTodos = new ArrayList();
        }
    }

    /**
     * Method called to associate a Todo object to this object
     * through the Todo foreign key attribute
     *
     * @param l Todo
     * @throws TorqueException
     */
    public void addTodo(Todo l) throws TorqueException
    {
        getTodos().add(l);
        l.setLkppriority((Lkppriority) this);
    }

    /**
     * The criteria used to select the current contents of collTodos
     */
    private Criteria lastTodosCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getTodos(new Criteria())
     *
     * @throws TorqueException
     */
    public List getTodos() throws TorqueException
    {
        if (collTodos == null)
        {
            collTodos = getTodos(new Criteria(10));
        }
        return collTodos;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority has previously
     * been saved, it will retrieve related Todos from storage.
     * If this Lkppriority is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getTodos(Criteria criteria) throws TorqueException
    {
        if (collTodos == null)
        {
            if (isNew())
            {
               collTodos = new ArrayList();
            }
            else
            {
                   criteria.add(TodoPeer.PRIORITYID, getPriorityid() );
                   collTodos = TodoPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(TodoPeer.PRIORITYID, getPriorityid());
                   if (!lastTodosCriteria.equals(criteria))
                {
                    collTodos = TodoPeer.doSelect(criteria);
                }
            }
        }
        lastTodosCriteria = criteria;

        return collTodos;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getTodos(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getTodos(Connection con) throws TorqueException
    {
        if (collTodos == null)
        {
            collTodos = getTodos(new Criteria(10), con);
        }
        return collTodos;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority has previously
     * been saved, it will retrieve related Todos from storage.
     * If this Lkppriority is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getTodos(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collTodos == null)
        {
            if (isNew())
            {
               collTodos = new ArrayList();
            }
            else
            {
                     criteria.add(TodoPeer.PRIORITYID, getPriorityid());
                     collTodos = TodoPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(TodoPeer.PRIORITYID, getPriorityid());
                     if (!lastTodosCriteria.equals(criteria))
                 {
                     collTodos = TodoPeer.doSelect(criteria, con);
                 }
             }
         }
         lastTodosCriteria = criteria;

         return collTodos;
     }

      

     
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority is new, it will return
     * an empty collection; or if this Lkppriority has previously
     * been saved, it will retrieve related Todos from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Lkppriority.
     */
    protected List getTodosJoinProject(Criteria criteria)
        throws TorqueException
    {
        if (collTodos == null)
        {
            if (isNew())
            {
               collTodos = new ArrayList();
            }
            else
            {
                   criteria.add(TodoPeer.PRIORITYID, getPriorityid());
                   collTodos = TodoPeer.doSelectJoinProject(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TodoPeer.PRIORITYID, getPriorityid());
               if (!lastTodosCriteria.equals(criteria))
            {
                collTodos = TodoPeer.doSelectJoinProject(criteria);
            }
        }
        lastTodosCriteria = criteria;

        return collTodos;
    }
   
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority is new, it will return
     * an empty collection; or if this Lkppriority has previously
     * been saved, it will retrieve related Todos from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Lkppriority.
     */
    protected List getTodosJoinLkptype(Criteria criteria)
        throws TorqueException
    {
        if (collTodos == null)
        {
            if (isNew())
            {
               collTodos = new ArrayList();
            }
            else
            {
                   criteria.add(TodoPeer.PRIORITYID, getPriorityid());
                   collTodos = TodoPeer.doSelectJoinLkptype(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TodoPeer.PRIORITYID, getPriorityid());
               if (!lastTodosCriteria.equals(criteria))
            {
                collTodos = TodoPeer.doSelectJoinLkptype(criteria);
            }
        }
        lastTodosCriteria = criteria;

        return collTodos;
    }
   
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority is new, it will return
     * an empty collection; or if this Lkppriority has previously
     * been saved, it will retrieve related Todos from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Lkppriority.
     */
    protected List getTodosJoinLkpstatus(Criteria criteria)
        throws TorqueException
    {
        if (collTodos == null)
        {
            if (isNew())
            {
               collTodos = new ArrayList();
            }
            else
            {
                   criteria.add(TodoPeer.PRIORITYID, getPriorityid());
                   collTodos = TodoPeer.doSelectJoinLkpstatus(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TodoPeer.PRIORITYID, getPriorityid());
               if (!lastTodosCriteria.equals(criteria))
            {
                collTodos = TodoPeer.doSelectJoinLkpstatus(criteria);
            }
        }
        lastTodosCriteria = criteria;

        return collTodos;
    }
   
      
         
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority is new, it will return
     * an empty collection; or if this Lkppriority has previously
     * been saved, it will retrieve related Todos from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Lkppriority.
     */
    protected List getTodosJoinLkppriority(Criteria criteria)
        throws TorqueException
    {
        if (collTodos == null)
        {
            if (isNew())
            {
               collTodos = new ArrayList();
            }
            else
            {
                   criteria.add(TodoPeer.PRIORITYID, getPriorityid());
                   collTodos = TodoPeer.doSelectJoinLkppriority(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TodoPeer.PRIORITYID, getPriorityid());
               if (!lastTodosCriteria.equals(criteria))
            {
                collTodos = TodoPeer.doSelectJoinLkppriority(criteria);
            }
        }
        lastTodosCriteria = criteria;

        return collTodos;
    }
     



             
      
    /**
     * Collection to store aggregation of collTaskestimates
     */
    protected List collTaskestimates;

    /**
     * Temporary storage of collTaskestimates to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initTaskestimates()
    {
        if (collTaskestimates == null)
        {
            collTaskestimates = new ArrayList();
        }
    }

    /**
     * Method called to associate a Taskestimate object to this object
     * through the Taskestimate foreign key attribute
     *
     * @param l Taskestimate
     * @throws TorqueException
     */
    public void addTaskestimate(Taskestimate l) throws TorqueException
    {
        getTaskestimates().add(l);
        l.setLkppriority((Lkppriority) this);
    }

    /**
     * The criteria used to select the current contents of collTaskestimates
     */
    private Criteria lastTaskestimatesCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getTaskestimates(new Criteria())
     *
     * @throws TorqueException
     */
    public List getTaskestimates() throws TorqueException
    {
        if (collTaskestimates == null)
        {
            collTaskestimates = getTaskestimates(new Criteria(10));
        }
        return collTaskestimates;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority has previously
     * been saved, it will retrieve related Taskestimates from storage.
     * If this Lkppriority is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getTaskestimates(Criteria criteria) throws TorqueException
    {
        if (collTaskestimates == null)
        {
            if (isNew())
            {
               collTaskestimates = new ArrayList();
            }
            else
            {
                   criteria.add(TaskestimatePeer.PRIORITYID, getPriorityid() );
                   collTaskestimates = TaskestimatePeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(TaskestimatePeer.PRIORITYID, getPriorityid());
                   if (!lastTaskestimatesCriteria.equals(criteria))
                {
                    collTaskestimates = TaskestimatePeer.doSelect(criteria);
                }
            }
        }
        lastTaskestimatesCriteria = criteria;

        return collTaskestimates;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getTaskestimates(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getTaskestimates(Connection con) throws TorqueException
    {
        if (collTaskestimates == null)
        {
            collTaskestimates = getTaskestimates(new Criteria(10), con);
        }
        return collTaskestimates;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority has previously
     * been saved, it will retrieve related Taskestimates from storage.
     * If this Lkppriority is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getTaskestimates(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collTaskestimates == null)
        {
            if (isNew())
            {
               collTaskestimates = new ArrayList();
            }
            else
            {
                     criteria.add(TaskestimatePeer.PRIORITYID, getPriorityid());
                     collTaskestimates = TaskestimatePeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(TaskestimatePeer.PRIORITYID, getPriorityid());
                     if (!lastTaskestimatesCriteria.equals(criteria))
                 {
                     collTaskestimates = TaskestimatePeer.doSelect(criteria, con);
                 }
             }
         }
         lastTaskestimatesCriteria = criteria;

         return collTaskestimates;
     }

     

     
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority is new, it will return
     * an empty collection; or if this Lkppriority has previously
     * been saved, it will retrieve related Taskestimates from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Lkppriority.
     */
    protected List getTaskestimatesJoinTask(Criteria criteria)
        throws TorqueException
    {
        if (collTaskestimates == null)
        {
            if (isNew())
            {
               collTaskestimates = new ArrayList();
            }
            else
            {
                   criteria.add(TaskestimatePeer.PRIORITYID, getPriorityid());
                   collTaskestimates = TaskestimatePeer.doSelectJoinTask(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskestimatePeer.PRIORITYID, getPriorityid());
               if (!lastTaskestimatesCriteria.equals(criteria))
            {
                collTaskestimates = TaskestimatePeer.doSelectJoinTask(criteria);
            }
        }
        lastTaskestimatesCriteria = criteria;

        return collTaskestimates;
    }
   
      
         
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority is new, it will return
     * an empty collection; or if this Lkppriority has previously
     * been saved, it will retrieve related Taskestimates from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Lkppriority.
     */
    protected List getTaskestimatesJoinLkppriority(Criteria criteria)
        throws TorqueException
    {
        if (collTaskestimates == null)
        {
            if (isNew())
            {
               collTaskestimates = new ArrayList();
            }
            else
            {
                   criteria.add(TaskestimatePeer.PRIORITYID, getPriorityid());
                   collTaskestimates = TaskestimatePeer.doSelectJoinLkppriority(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskestimatePeer.PRIORITYID, getPriorityid());
               if (!lastTaskestimatesCriteria.equals(criteria))
            {
                collTaskestimates = TaskestimatePeer.doSelectJoinLkppriority(criteria);
            }
        }
        lastTaskestimatesCriteria = criteria;

        return collTaskestimates;
    }
   
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority is new, it will return
     * an empty collection; or if this Lkppriority has previously
     * been saved, it will retrieve related Taskestimates from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Lkppriority.
     */
    protected List getTaskestimatesJoinLkpmeasure(Criteria criteria)
        throws TorqueException
    {
        if (collTaskestimates == null)
        {
            if (isNew())
            {
               collTaskestimates = new ArrayList();
            }
            else
            {
                   criteria.add(TaskestimatePeer.PRIORITYID, getPriorityid());
                   collTaskestimates = TaskestimatePeer.doSelectJoinLkpmeasure(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskestimatePeer.PRIORITYID, getPriorityid());
               if (!lastTaskestimatesCriteria.equals(criteria))
            {
                collTaskestimates = TaskestimatePeer.doSelectJoinLkpmeasure(criteria);
            }
        }
        lastTaskestimatesCriteria = criteria;

        return collTaskestimates;
    }
     



             
      
    /**
     * Collection to store aggregation of collTaskactuals
     */
    protected List collTaskactuals;

    /**
     * Temporary storage of collTaskactuals to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initTaskactuals()
    {
        if (collTaskactuals == null)
        {
            collTaskactuals = new ArrayList();
        }
    }

    /**
     * Method called to associate a Taskactual object to this object
     * through the Taskactual foreign key attribute
     *
     * @param l Taskactual
     * @throws TorqueException
     */
    public void addTaskactual(Taskactual l) throws TorqueException
    {
        getTaskactuals().add(l);
        l.setLkppriority((Lkppriority) this);
    }

    /**
     * The criteria used to select the current contents of collTaskactuals
     */
    private Criteria lastTaskactualsCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getTaskactuals(new Criteria())
     *
     * @throws TorqueException
     */
    public List getTaskactuals() throws TorqueException
    {
        if (collTaskactuals == null)
        {
            collTaskactuals = getTaskactuals(new Criteria(10));
        }
        return collTaskactuals;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority has previously
     * been saved, it will retrieve related Taskactuals from storage.
     * If this Lkppriority is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getTaskactuals(Criteria criteria) throws TorqueException
    {
        if (collTaskactuals == null)
        {
            if (isNew())
            {
               collTaskactuals = new ArrayList();
            }
            else
            {
                   criteria.add(TaskactualPeer.PRIORITYID, getPriorityid() );
                   collTaskactuals = TaskactualPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(TaskactualPeer.PRIORITYID, getPriorityid());
                   if (!lastTaskactualsCriteria.equals(criteria))
                {
                    collTaskactuals = TaskactualPeer.doSelect(criteria);
                }
            }
        }
        lastTaskactualsCriteria = criteria;

        return collTaskactuals;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getTaskactuals(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getTaskactuals(Connection con) throws TorqueException
    {
        if (collTaskactuals == null)
        {
            collTaskactuals = getTaskactuals(new Criteria(10), con);
        }
        return collTaskactuals;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority has previously
     * been saved, it will retrieve related Taskactuals from storage.
     * If this Lkppriority is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getTaskactuals(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collTaskactuals == null)
        {
            if (isNew())
            {
               collTaskactuals = new ArrayList();
            }
            else
            {
                     criteria.add(TaskactualPeer.PRIORITYID, getPriorityid());
                     collTaskactuals = TaskactualPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(TaskactualPeer.PRIORITYID, getPriorityid());
                     if (!lastTaskactualsCriteria.equals(criteria))
                 {
                     collTaskactuals = TaskactualPeer.doSelect(criteria, con);
                 }
             }
         }
         lastTaskactualsCriteria = criteria;

         return collTaskactuals;
     }

     

     
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority is new, it will return
     * an empty collection; or if this Lkppriority has previously
     * been saved, it will retrieve related Taskactuals from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Lkppriority.
     */
    protected List getTaskactualsJoinTask(Criteria criteria)
        throws TorqueException
    {
        if (collTaskactuals == null)
        {
            if (isNew())
            {
               collTaskactuals = new ArrayList();
            }
            else
            {
                   criteria.add(TaskactualPeer.PRIORITYID, getPriorityid());
                   collTaskactuals = TaskactualPeer.doSelectJoinTask(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskactualPeer.PRIORITYID, getPriorityid());
               if (!lastTaskactualsCriteria.equals(criteria))
            {
                collTaskactuals = TaskactualPeer.doSelectJoinTask(criteria);
            }
        }
        lastTaskactualsCriteria = criteria;

        return collTaskactuals;
    }
   
      
         
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority is new, it will return
     * an empty collection; or if this Lkppriority has previously
     * been saved, it will retrieve related Taskactuals from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Lkppriority.
     */
    protected List getTaskactualsJoinLkppriority(Criteria criteria)
        throws TorqueException
    {
        if (collTaskactuals == null)
        {
            if (isNew())
            {
               collTaskactuals = new ArrayList();
            }
            else
            {
                   criteria.add(TaskactualPeer.PRIORITYID, getPriorityid());
                   collTaskactuals = TaskactualPeer.doSelectJoinLkppriority(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskactualPeer.PRIORITYID, getPriorityid());
               if (!lastTaskactualsCriteria.equals(criteria))
            {
                collTaskactuals = TaskactualPeer.doSelectJoinLkppriority(criteria);
            }
        }
        lastTaskactualsCriteria = criteria;

        return collTaskactuals;
    }
   
      
      
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Lkppriority is new, it will return
     * an empty collection; or if this Lkppriority has previously
     * been saved, it will retrieve related Taskactuals from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Lkppriority.
     */
    protected List getTaskactualsJoinLkpmeasure(Criteria criteria)
        throws TorqueException
    {
        if (collTaskactuals == null)
        {
            if (isNew())
            {
               collTaskactuals = new ArrayList();
            }
            else
            {
                   criteria.add(TaskactualPeer.PRIORITYID, getPriorityid());
                   collTaskactuals = TaskactualPeer.doSelectJoinLkpmeasure(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(TaskactualPeer.PRIORITYID, getPriorityid());
               if (!lastTaskactualsCriteria.equals(criteria))
            {
                collTaskactuals = TaskactualPeer.doSelectJoinLkpmeasure(criteria);
            }
        }
        lastTaskactualsCriteria = criteria;

        return collTaskactuals;
    }
     



     
    
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
      if (fieldNames == null)
      {
        fieldNames = new ArrayList();
            fieldNames.add("Priorityid");
            fieldNames.add("Name");
            fieldNames.add("Description");
            fieldNames = Collections.unmodifiableList(fieldNames);
      }
      return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
            if (name.equals("Priorityid"))
    {
              return new Integer(getPriorityid());
          }
            if (name.equals("Name"))
    {
              return getName();
          }
            if (name.equals("Description"))
    {
              return getDescription();
          }
            return null;
    }
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
            if (name.equals(LkppriorityPeer.PRIORITYID))
        {
              return new Integer(getPriorityid());
          }
            if (name.equals(LkppriorityPeer.NAME))
        {
              return getName();
          }
            if (name.equals(LkppriorityPeer.DESCRIPTION))
        {
              return getDescription();
          }
            return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
    {
              return new Integer(getPriorityid());
          }
            if (pos == 1)
    {
              return getName();
          }
            if (pos == 2)
    {
              return getDescription();
          }
                return null;
    }

     


    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
             save(LkppriorityPeer.getMapBuilder()
                .getDatabaseMap().getName());
     }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
         try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }

     }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;



  
        // If this object has been modified, then save it to the database.
        if (isModified())
        {
            if (isNew())
            {
                LkppriorityPeer.doInsert((Lkppriority) this, con);
                setNew(false);
            }
            else
            {
                LkppriorityPeer.doUpdate((Lkppriority) this, con);
            }
        }

                                    
                
          if (collTasks != null)
          {
              for (int i = 0; i < collTasks.size(); i++)
              {
                  ((Task) collTasks.get(i)).save(con);
              }
          }
                                        
                
          if (collTodos != null)
          {
              for (int i = 0; i < collTodos.size(); i++)
              {
                  ((Todo) collTodos.get(i)).save(con);
              }
          }
                                        
                
          if (collTaskestimates != null)
          {
              for (int i = 0; i < collTaskestimates.size(); i++)
              {
                  ((Taskestimate) collTaskestimates.get(i)).save(con);
              }
          }
                                        
                
          if (collTaskactuals != null)
          {
              for (int i = 0; i < collTaskactuals.size(); i++)
              {
                  ((Taskactual) collTaskactuals.get(i)).save(con);
              }
          }
                  alreadyInSave = false;
      }
      }


                        
    
    

        /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  priorityid ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
                    setPriorityid(((NumberKey) key).intValue());
            }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
                    setPriorityid(Integer.parseInt(key));
            }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getPriorityid());
    }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Lkppriority copy() throws TorqueException
    {
        return copyInto(new Lkppriority());
    }

    protected Lkppriority copyInto(Lkppriority copyObj) throws TorqueException
    {
        copyObj.setPriorityid(priorityid);
        copyObj.setName(name);
        copyObj.setDescription(description);

                      copyObj.setPriorityid(0);
                    

                                  
                
        List v = getTasks();
        for (int i = 0; i < v.size(); i++)
        {
            Task obj = (Task) v.get(i);
            copyObj.addTask(obj.copy());
        }
                                              
                
        v = getTodos();
        for (int i = 0; i < v.size(); i++)
        {
            Todo obj = (Todo) v.get(i);
            copyObj.addTodo(obj.copy());
        }
                                              
                
        v = getTaskestimates();
        for (int i = 0; i < v.size(); i++)
        {
            Taskestimate obj = (Taskestimate) v.get(i);
            copyObj.addTaskestimate(obj.copy());
        }
                                              
                
        v = getTaskactuals();
        for (int i = 0; i < v.size(); i++)
        {
            Taskactual obj = (Taskactual) v.get(i);
            copyObj.addTaskactual(obj.copy());
        }
              
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public LkppriorityPeer getPeer()
    {
        return peer;
    }
}
