package com.sns.scout.managers;

import java.util.Iterator;
import java.util.List;
import org.apache.torque.util.Criteria;

import com.sns.util.Utility;

/** 
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Mar 14 14:37:34 CDT 2008]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class GroupsPeer 
    extends com.sns.scout.managers.BaseGroupsPeer
{

	/**
	 * This method returns a list of Project objects where each Project object
	 * maps to a row in the database. This is primarily for drop down lists
	 * in the GUI. 
	 *
	 * @return Project[] 
	 */
	static public List getGroups() {
		List retVal = null;
		
		Criteria crit = new Criteria();
	
		try {
			crit.setAll();
			retVal = GroupsPeer.doSelect(crit);
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return retVal;
	}
	
	/**
	 * This method returns a list of Groups objects where each Groups object
	 * maps to a row in the database. This is primarily for drop down lists
	 * in the GUI. 
	 *
	 * @return Groups[] 
	 */
	static public Groups [] getGroupsList() {
		Groups theList[] = new Groups[Utility.numRows("Groups")];
		int count=0;
		
		Criteria crit = new Criteria();

		try {
			List result = GroupsPeer.doSelect(crit);
			Iterator it = result.iterator();
			
			while (it.hasNext()) {
				theList[count++] = (Groups) it.next();  
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return theList;
	}
}
