package com.sns.scout.managers;

import java.util.Iterator;
import java.util.List;

import org.apache.torque.util.Criteria;

import com.sns.util.Utility;

/** 
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sun Jul 29 08:18:03 CDT 2007]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class LkppriorityPeer 
    extends com.sns.scout.managers.BaseLkppriorityPeer
{

	/**
	 * This method simply returns a list of Lkppriority objects where each 
	 * Lkppriority object maps to a row in the database. This is primarily
	 * for drop down lists in the GUI. 
	 * 
	 * @return Lkppriority[] 
	 */
	static public Lkppriority [] getPriorityList() {
		Lkppriority theList[] = new Lkppriority[Utility.numRows("lkpPriority")];
		int count=0;
		
		Criteria crit = new Criteria();
	
		try {
			List result = LkppriorityPeer.doSelect(crit);
			Iterator it = result.iterator();
			
			while (it.hasNext()) {
				theList[count++] = (Lkppriority) it.next();  
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return theList;
	}
}
