package com.sns.scout.managers;

import java.util.Iterator;
import java.util.List;
import org.apache.torque.util.Criteria;

import com.sns.util.Utility;

/** 
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Mar 14 14:37:34 CDT 2008]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class UsersPeer 
    extends com.sns.scout.managers.BaseUsersPeer
{

	/**
	 * This method returns a list of Users objects where each Users object
	 * maps to a row in the database. This is primarily for drop down lists
	 * in the GUI. 
	 *
	 * @return Users[] 
	 */
	static public List getUsers() {
		List retVal = null;
		
		Criteria crit = new Criteria();
	
		try {
			crit.setAll();
			retVal = UsersPeer.doSelect(crit);
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return retVal;
	}
	
	
	/**
	 * This method returns a list of Users objects where each Users object
	 * maps to a row in the database. This is primarily for drop down lists
	 * in the GUI. 
	 *
	 * @return Users[] 
	 */
	static public Users [] getUsersList() {
		Users theList[] = new Users[Utility.numRows("Users")];
		int count=0;
		
		Criteria crit = new Criteria();

		try {
			List result = UsersPeer.doSelect(crit);
			Iterator it = result.iterator();
			
			while (it.hasNext()) {
				theList[count++] = (Users) it.next();  
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return theList;
	}
}
