
package com.hungrymutt.managers;


import org.apache.torque.om.Persistent;

/** 
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sun Dec 12 11:27:33 CST 2004]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Ratings 
    extends com.hungrymutt.managers.BaseRatings
    implements Persistent
{
}
