package com.sns.teammgr.managers;



import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;

   
   
/**
 * This class was autogenerated by Torque on:
 *
 * [Tue Feb 19 16:03:50 CST 2008]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Gamecomments
 */
public abstract class BaseGamecomments extends BaseObject
{
    /** The Peer class */
    private static final GamecommentsPeer peer =
        new GamecommentsPeer();

                  
        /**
         * The value for the commentid field
         */
        private int commentid;
              
        /**
         * The value for the gameid field
         */
        private int gameid;
              
        /**
         * The value for the msg field
         */
        private String msg;
      
      
        /**
         * Get the Commentid
         *
         * @return int
         */
        public int getCommentid()
        {
            return commentid;
        }

                                            
        /**
         * Set the value of Commentid
         *
         * @param v new value
         */
        public void setCommentid(int v) 
        {
          


         if (this.commentid != v)
        {
             this.commentid = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Gameid
         *
         * @return int
         */
        public int getGameid()
        {
            return gameid;
        }

                                                      
        /**
         * Set the value of Gameid
         *
         * @param v new value
         */
        public void setGameid(int v) throws TorqueException
        {
          


         if (this.gameid != v)
        {
             this.gameid = v;
            setModified(true);
        }

                                          
                if (aGame != null && !(aGame.getGameid()==v))
                {
            aGame = null;
        }
          
                       }


        /**
         * Get the Msg
         *
         * @return String
         */
        public String getMsg()
        {
            return msg;
        }

                                            
        /**
         * Set the value of Msg
         *
         * @param v new value
         */
        public void setMsg(String v) 
        {
          


         if (!ObjectUtils.equals(this.msg, v))
        {
             this.msg = v;
            setModified(true);
        }

                  
                       }


 
     
   
             
   
       private Game aGame;

    /**
     * Declares an association between this object and a Game object
     *
     * @param v Game
     * @throws TorqueException
     */
    public void setGame(Game v) throws TorqueException
    {
           if (v == null)
        {
                        setGameid(0);
                    }
        else
        {
            setGameid(v.getGameid());
        }
           aGame = v;
    }

                 
    /**
     * Get the associated Game object
     *
     * @return the associated Game object
     * @throws TorqueException
     */
    public Game getGame() throws TorqueException
    {
        if (aGame == null && (this.gameid > 0))
        {
              aGame = GamePeer.retrieveByPK(SimpleKey.keyFor(this.gameid));
      
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               Game obj = GamePeer.retrieveByPK(this.gameid);
               obj.addGamecommentss(this);
             */
        }
        return aGame;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setGameKey(ObjectKey key) throws TorqueException
    {
    
                                        setGameid(((NumberKey) key).intValue());
                    }
    
        
    
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
      if (fieldNames == null)
      {
        fieldNames = new ArrayList();
            fieldNames.add("Commentid");
            fieldNames.add("Gameid");
            fieldNames.add("Msg");
            fieldNames = Collections.unmodifiableList(fieldNames);
      }
      return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
            if (name.equals("Commentid"))
    {
              return new Integer(getCommentid());
          }
            if (name.equals("Gameid"))
    {
              return new Integer(getGameid());
          }
            if (name.equals("Msg"))
    {
              return getMsg();
          }
            return null;
    }
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
            if (name.equals(GamecommentsPeer.COMMENTID))
        {
              return new Integer(getCommentid());
          }
            if (name.equals(GamecommentsPeer.GAMEID))
        {
              return new Integer(getGameid());
          }
            if (name.equals(GamecommentsPeer.MSG))
        {
              return getMsg();
          }
            return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
    {
              return new Integer(getCommentid());
          }
            if (pos == 1)
    {
              return new Integer(getGameid());
          }
            if (pos == 2)
    {
              return getMsg();
          }
                return null;
    }

     


    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
             save(GamecommentsPeer.getMapBuilder()
                .getDatabaseMap().getName());
     }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
         try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }

     }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;



  
        // If this object has been modified, then save it to the database.
        if (isModified())
        {
            if (isNew())
            {
                GamecommentsPeer.doInsert((Gamecomments) this, con);
                setNew(false);
            }
            else
            {
                GamecommentsPeer.doUpdate((Gamecomments) this, con);
            }
        }

              alreadyInSave = false;
      }
      }


                
    
    

        /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  commentid ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        
    {
                    setCommentid(((NumberKey) key).intValue());
            }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) 
    {
                    setCommentid(Integer.parseInt(key));
            }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getCommentid());
    }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Gamecomments copy() throws TorqueException
    {
        return copyInto(new Gamecomments());
    }

    protected Gamecomments copyInto(Gamecomments copyObj) throws TorqueException
    {
        copyObj.setCommentid(commentid);
        copyObj.setGameid(gameid);
        copyObj.setMsg(msg);

                      copyObj.setCommentid(0);
                    

  
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public GamecommentsPeer getPeer()
    {
        return peer;
    }
}
