package com.sns.teammgr.managers;

import org.apache.torque.util.Criteria;

/** 
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Aug 03 14:22:15 CDT 2007]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class LinkPeer 
    extends com.sns.teammgr.managers.BaseLinkPeer
{
	static public void delete(String theId) {
		int currentId = Integer.parseInt(theId);
	
		Criteria crit = new Criteria();
	
		try {
			crit.add(LinkPeer.LINKID, currentId);
			crit.setAll();
			LinkPeer.doDelete(crit);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
