package com.sns.teammgr.managers.map;

import java.util.Date;


import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Tue Feb 19 16:03:50 CST 2008]
  *
  */
public class GameMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "com.sns.teammgr.managers.map.GameMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("teammgr");

        dbMap.addTable("Game");
        TableMap tMap = dbMap.getTable("Game");

                tMap.setPrimaryKeyMethod(TableMap.ID_BROKER);
        
                tMap.setPrimaryKeyMethodInfo(tMap.getName());
        
                                      tMap.addPrimaryKey("Game.GAMEID", new Integer(0));
                                                        tMap.addForeignKey(
                "Game.TEAMID", new Integer(0) , "Team" ,
                    "teamID");
                                                        tMap.addForeignKey(
                "Game.GOALIEID", new Integer(0) , "Player" ,
                    "playerID");
                                                        tMap.addColumn("Game.SCOREUS", new Integer(0));
                                                        tMap.addColumn("Game.SCORETHEM", new Integer(0));
                                                        tMap.addColumn("Game.RESULT", new Integer(0));
                                                        tMap.addColumn("Game.OPPONENT", new String());
                                                        tMap.addColumn("Game.SUMMARY", new String());
                                                        tMap.addColumn("Game.PERIOD1", new String());
                                                        tMap.addColumn("Game.PERIOD2", new String());
                                                        tMap.addColumn("Game.PERIOD3", new String());
                                                        tMap.addColumn("Game.OVERTIME", new String());
                                                        tMap.addColumn("Game.HIGHLIGHT", new String());
                                                        tMap.addColumn("Game.BOTTOMLINE", new String());
                                                        tMap.addColumn("Game.STAR1", new String());
                                                        tMap.addColumn("Game.STAR2", new String());
                                                        tMap.addColumn("Game.STAR3", new String());
                              }
}
