package com.hungrymutt.managers;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;


/**
 * This class was autogenerated by Torque on:
 *
 * [Sun Dec 12 11:27:33 CST 2004]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Recipes
 */
public abstract class BaseRecipes extends BaseObject
{
    /** The Peer class */
    private static final RecipesPeer peer =
        new RecipesPeer();

                  
        /**
         * The value for the recipeid field
         */
        private int recipeid;
              
        /**
         * The value for the title field
         */
        private String title;
              
        /**
         * The value for the submittedby field
         */
        private String submittedby;
              
        /**
         * The value for the recipebody field
         */
        private byte[] recipebody;
              
        /**
         * The value for the recipecategory field
         */
        private String recipecategory;
              
        /**
         * The value for the visible field
         */
        private boolean visible;
              
        /**
         * The value for the datesubmitted field
         */
        private Date datesubmitted;
      
      
        /**
         * Get the Recipeid
         *
         * @return int
         */
        public int getRecipeid()
        {
            return recipeid;
        }

                                                                              
        /**
         * Set the value of Recipeid
         *
         * @param v new value
         */
        public void setRecipeid(int v) throws TorqueException
        {
          


         if (this.recipeid != v)
        {
             this.recipeid = v;
            setModified(true);
        }

                  
                                                  
              // update associated Ratings
              if (collRatingss != null)
              {
                  for (int i = 0; i < collRatingss.size(); i++)
                  {
                      ((Ratings) collRatingss.get(i))
                          .setRecipeid(v);
                  }
              }
                                   }


        /**
         * Get the Title
         *
         * @return String
         */
        public String getTitle()
        {
            return title;
        }

                                            
        /**
         * Set the value of Title
         *
         * @param v new value
         */
        public void setTitle(String v) 
        {
          


         if (!ObjectUtils.equals(this.title, v))
        {
             this.title = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Submittedby
         *
         * @return String
         */
        public String getSubmittedby()
        {
            return submittedby;
        }

                                            
        /**
         * Set the value of Submittedby
         *
         * @param v new value
         */
        public void setSubmittedby(String v) 
        {
          


         if (!ObjectUtils.equals(this.submittedby, v))
        {
             this.submittedby = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Recipebody
         *
         * @return byte[]
         */
        public byte[] getRecipebody()
        {
            return recipebody;
        }

                                            
        /**
         * Set the value of Recipebody
         *
         * @param v new value
         */
        public void setRecipebody(byte[] v) 
        {
          


         if (!ObjectUtils.equals(this.recipebody, v))
        {
             this.recipebody = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Recipecategory
         *
         * @return String
         */
        public String getRecipecategory()
        {
            return recipecategory;
        }

                                            
        /**
         * Set the value of Recipecategory
         *
         * @param v new value
         */
        public void setRecipecategory(String v) 
        {
          


         if (!ObjectUtils.equals(this.recipecategory, v))
        {
             this.recipecategory = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Visible
         *
         * @return boolean
         */
        public boolean getVisible()
        {
            return visible;
        }

                                            
        /**
         * Set the value of Visible
         *
         * @param v new value
         */
        public void setVisible(boolean v) 
        {
          


         if (this.visible != v)
        {
             this.visible = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the Datesubmitted
         *
         * @return Date
         */
        public Date getDatesubmitted()
        {
            return datesubmitted;
        }

                                            
        /**
         * Set the value of Datesubmitted
         *
         * @param v new value
         */
        public void setDatesubmitted(Date v) 
        {
          


         if (!ObjectUtils.equals(this.datesubmitted, v))
        {
             this.datesubmitted = v;
            setModified(true);
        }

                  
                       }


 
        
                
      
    /**
     * Collection to store aggregation of collRatingss
     */
    protected List collRatingss;

    /**
     * Temporary storage of collRatingss to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initRatingss()
    {
        if (collRatingss == null)
        {
            collRatingss = new ArrayList();
        }
    }

    /**
     * Method called to associate a Ratings object to this object
     * through the Ratings foreign key attribute
     *
     * @param l Ratings
     * @throws TorqueException
     */
    public void addRatings(Ratings l) throws TorqueException
    {
        getRatingss().add(l);
        l.setRecipes((Recipes) this);
    }

    /**
     * The criteria used to select the current contents of collRatingss
     */
    private Criteria lastRatingssCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getRatingss(new Criteria())
     *
     * @throws TorqueException
     */
    public List getRatingss() throws TorqueException
    {
        if (collRatingss == null)
        {
            collRatingss = getRatingss(new Criteria(10));
        }
        return collRatingss;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Recipes has previously
     * been saved, it will retrieve related Ratingss from storage.
     * If this Recipes is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getRatingss(Criteria criteria) throws TorqueException
    {
        if (collRatingss == null)
        {
            if (isNew())
            {
               collRatingss = new ArrayList();
            }
            else
            {
                   criteria.add(RatingsPeer.RECIPEID, getRecipeid() );
                   collRatingss = RatingsPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(RatingsPeer.RECIPEID, getRecipeid());
                   if (!lastRatingssCriteria.equals(criteria))
                {
                    collRatingss = RatingsPeer.doSelect(criteria);
                }
            }
        }
        lastRatingssCriteria = criteria;

        return collRatingss;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getRatingss(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getRatingss(Connection con) throws TorqueException
    {
        if (collRatingss == null)
        {
            collRatingss = getRatingss(new Criteria(10), con);
        }
        return collRatingss;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Recipes has previously
     * been saved, it will retrieve related Ratingss from storage.
     * If this Recipes is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getRatingss(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collRatingss == null)
        {
            if (isNew())
            {
               collRatingss = new ArrayList();
            }
            else
            {
                     criteria.add(RatingsPeer.RECIPEID, getRecipeid());
                     collRatingss = RatingsPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(RatingsPeer.RECIPEID, getRecipeid());
                     if (!lastRatingssCriteria.equals(criteria))
                 {
                     collRatingss = RatingsPeer.doSelect(criteria, con);
                 }
             }
         }
         lastRatingssCriteria = criteria;

         return collRatingss;
     }

   

     
      
         
          
                            
                
        
        
   
    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Recipes is new, it will return
     * an empty collection; or if this Recipes has previously
     * been saved, it will retrieve related Ratingss from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in Recipes.
     */
    protected List getRatingssJoinRecipes(Criteria criteria)
        throws TorqueException
    {
        if (collRatingss == null)
        {
            if (isNew())
            {
               collRatingss = new ArrayList();
            }
            else
            {
                   criteria.add(RatingsPeer.RECIPEID, getRecipeid());
                   collRatingss = RatingsPeer.doSelectJoinRecipes(criteria);
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            boolean newCriteria = true;
                   criteria.add(RatingsPeer.RECIPEID, getRecipeid());
               if (!lastRatingssCriteria.equals(criteria))
            {
                collRatingss = RatingsPeer.doSelectJoinRecipes(criteria);
            }
        }
        lastRatingssCriteria = criteria;

        return collRatingss;
    }
     



     
    
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
      if (fieldNames == null)
      {
        fieldNames = new ArrayList();
            fieldNames.add("Recipeid");
            fieldNames.add("Title");
            fieldNames.add("Submittedby");
            fieldNames.add("Recipebody");
            fieldNames.add("Recipecategory");
            fieldNames.add("Visible");
            fieldNames.add("Datesubmitted");
            fieldNames = Collections.unmodifiableList(fieldNames);
      }
      return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
            if (name.equals("Recipeid"))
    {
              return new Integer(getRecipeid());
          }
            if (name.equals("Title"))
    {
              return getTitle();
          }
            if (name.equals("Submittedby"))
    {
              return getSubmittedby();
          }
            if (name.equals("Recipebody"))
    {
              return getRecipebody();
          }
            if (name.equals("Recipecategory"))
    {
              return getRecipecategory();
          }
            if (name.equals("Visible"))
    {
              return new Boolean(getVisible());
          }
            if (name.equals("Datesubmitted"))
    {
              return getDatesubmitted();
          }
            return null;
    }
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
            if (name.equals(RecipesPeer.RECIPEID))
        {
              return new Integer(getRecipeid());
          }
            if (name.equals(RecipesPeer.TITLE))
        {
              return getTitle();
          }
            if (name.equals(RecipesPeer.SUBMITTEDBY))
        {
              return getSubmittedby();
          }
            if (name.equals(RecipesPeer.RECIPEBODY))
        {
              return getRecipebody();
          }
            if (name.equals(RecipesPeer.RECIPECATEGORY))
        {
              return getRecipecategory();
          }
            if (name.equals(RecipesPeer.VISIBLE))
        {
              return new Boolean(getVisible());
          }
            if (name.equals(RecipesPeer.DATESUBMITTED))
        {
              return getDatesubmitted();
          }
            return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
    {
              return new Integer(getRecipeid());
          }
            if (pos == 1)
    {
              return getTitle();
          }
            if (pos == 2)
    {
              return getSubmittedby();
          }
            if (pos == 3)
    {
              return getRecipebody();
          }
            if (pos == 4)
    {
              return getRecipecategory();
          }
            if (pos == 5)
    {
              return new Boolean(getVisible());
          }
            if (pos == 6)
    {
              return getDatesubmitted();
          }
                return null;
    }

     


    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
             save(RecipesPeer.getMapBuilder()
                .getDatabaseMap().getName());
     }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
         try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }

     }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;



  
        // If this object has been modified, then save it to the database.
        if (isModified())
        {
            if (isNew())
            {
                RecipesPeer.doInsert((Recipes) this, con);
                setNew(false);
            }
            else
            {
                RecipesPeer.doUpdate((Recipes) this, con);
            }
        }

                                    
                
          if (collRatingss != null)
          {
              for (int i = 0; i < collRatingss.size(); i++)
              {
                  ((Ratings) collRatingss.get(i)).save(con);
              }
          }
                  alreadyInSave = false;
      }
      }


                        
    
    

        /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  recipeid ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
                    setRecipeid(((NumberKey) key).intValue());
            }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
                    setRecipeid(Integer.parseInt(key));
            }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getRecipeid());
    }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Recipes copy() throws TorqueException
    {
        return copyInto(new Recipes());
    }

    protected Recipes copyInto(Recipes copyObj) throws TorqueException
    {
        copyObj.setRecipeid(recipeid);
        copyObj.setTitle(title);
        copyObj.setSubmittedby(submittedby);
        copyObj.setRecipebody(recipebody);
        copyObj.setRecipecategory(recipecategory);
        copyObj.setVisible(visible);
        copyObj.setDatesubmitted(datesubmitted);

                      copyObj.setRecipeid(0);
                                    

                                  
                
        List v = getRatingss();
        for (int i = 0; i < v.size(); i++)
        {
            Ratings obj = (Ratings) v.get(i);
            copyObj.addRatings(obj.copy());
        }
              
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public RecipesPeer getPeer()
    {
        return peer;
    }
}
