package com.sns.security.managers;



import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;

   
      
   
/**
 * This class was autogenerated by Torque on:
 *
 * [Fri Mar 07 11:01:56 CST 2008]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Secuserapp
 */
public abstract class BaseSecuserapp extends BaseObject
{
    /** The Peer class */
    private static final SecuserappPeer peer =
        new SecuserappPeer();

                  
        /**
         * The value for the appid field
         */
        private int appid;
              
        /**
         * The value for the secuserid field
         */
        private int secuserid;
      
      
        /**
         * Get the Appid
         *
         * @return int
         */
        public int getAppid()
        {
            return appid;
        }

                                                      
        /**
         * Set the value of Appid
         *
         * @param v new value
         */
        public void setAppid(int v) throws TorqueException
        {
          


         if (this.appid != v)
        {
             this.appid = v;
            setModified(true);
        }

                                          
                if (aSecapp != null && !(aSecapp.getAppid()==v))
                {
            aSecapp = null;
        }
          
                       }


        /**
         * Get the Secuserid
         *
         * @return int
         */
        public int getSecuserid()
        {
            return secuserid;
        }

                                                      
        /**
         * Set the value of Secuserid
         *
         * @param v new value
         */
        public void setSecuserid(int v) throws TorqueException
        {
          


         if (this.secuserid != v)
        {
             this.secuserid = v;
            setModified(true);
        }

                                          
                if (aSecuser != null && !(aSecuser.getSecuserid()==v))
                {
            aSecuser = null;
        }
          
                       }


 
     
   
             
   
       private Secuser aSecuser;

    /**
     * Declares an association between this object and a Secuser object
     *
     * @param v Secuser
     * @throws TorqueException
     */
    public void setSecuser(Secuser v) throws TorqueException
    {
           if (v == null)
        {
                        setSecuserid(0);
                    }
        else
        {
            setSecuserid(v.getSecuserid());
        }
           aSecuser = v;
    }

                 
    /**
     * Get the associated Secuser object
     *
     * @return the associated Secuser object
     * @throws TorqueException
     */
    public Secuser getSecuser() throws TorqueException
    {
        if (aSecuser == null && (this.secuserid > 0))
        {
              aSecuser = SecuserPeer.retrieveByPK(SimpleKey.keyFor(this.secuserid));
      
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               Secuser obj = SecuserPeer.retrieveByPK(this.secuserid);
               obj.addSecuserapps(this);
             */
        }
        return aSecuser;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setSecuserKey(ObjectKey key) throws TorqueException
    {
    
                                        setSecuserid(((NumberKey) key).intValue());
                    }
 
   
             
   
       private Secapp aSecapp;

    /**
     * Declares an association between this object and a Secapp object
     *
     * @param v Secapp
     * @throws TorqueException
     */
    public void setSecapp(Secapp v) throws TorqueException
    {
           if (v == null)
        {
                        setAppid(0);
                    }
        else
        {
            setAppid(v.getAppid());
        }
           aSecapp = v;
    }

                 
    /**
     * Get the associated Secapp object
     *
     * @return the associated Secapp object
     * @throws TorqueException
     */
    public Secapp getSecapp() throws TorqueException
    {
        if (aSecapp == null && (this.appid > 0))
        {
              aSecapp = SecappPeer.retrieveByPK(SimpleKey.keyFor(this.appid));
      
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               Secapp obj = SecappPeer.retrieveByPK(this.appid);
               obj.addSecuserapps(this);
             */
        }
        return aSecapp;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     */
    public void setSecappKey(ObjectKey key) throws TorqueException
    {
    
                                        setAppid(((NumberKey) key).intValue());
                    }
    
        
    
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
      if (fieldNames == null)
      {
        fieldNames = new ArrayList();
            fieldNames.add("Appid");
            fieldNames.add("Secuserid");
            fieldNames = Collections.unmodifiableList(fieldNames);
      }
      return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
            if (name.equals("Appid"))
    {
              return new Integer(getAppid());
          }
            if (name.equals("Secuserid"))
    {
              return new Integer(getSecuserid());
          }
            return null;
    }
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
            if (name.equals(SecuserappPeer.APPID))
        {
              return new Integer(getAppid());
          }
            if (name.equals(SecuserappPeer.SECUSERID))
        {
              return new Integer(getSecuserid());
          }
            return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
    {
              return new Integer(getAppid());
          }
            if (pos == 1)
    {
              return new Integer(getSecuserid());
          }
                return null;
    }

     


    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
             save(SecuserappPeer.getMapBuilder()
                .getDatabaseMap().getName());
     }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
         try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }

     }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;



  
        // If this object has been modified, then save it to the database.
        if (isModified())
        {
            if (isNew())
            {
                SecuserappPeer.doInsert((Secuserapp) this, con);
                setNew(false);
            }
            else
            {
                SecuserappPeer.doUpdate((Secuserapp) this, con);
            }
        }

              alreadyInSave = false;
      }
      }




    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return null;
    }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Secuserapp copy() throws TorqueException
    {
        return copyInto(new Secuserapp());
    }

    protected Secuserapp copyInto(Secuserapp copyObj) throws TorqueException
    {
        copyObj.setAppid(appid);
        copyObj.setSecuserid(secuserid);

        

  
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public SecuserappPeer getPeer()
    {
        return peer;
    }
}
