package com.sns.security.managers;

import java.util.List;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.util.Criteria;

import com.sns.scout.struts.Constants;
import com.sns.security.managers.BaseSecuserPeer;
import com.sns.security.managers.Secuser;

/**
 * The skeleton for this class was autogenerated by Torque on:
 * 
 * [Sun Jun 10 18:35:09 CDT 2007]
 * 
 * You should add additional methods to this class to meet the application
 * requirements. This class will only be generated as long as it does not
 * already exist in the output directory.
 */
public class SecuserPeer extends com.sns.security.managers.BaseSecuserPeer {

	static public Secuser simpleLogin(String uid, String pwd) {
		Secuser retVal = null;

		try {
			if (!Torque.isInit()) {
				Torque.init(Constants.TorqueHome);
			}
			
			Criteria crit = new Criteria();

			/* Only use for search if the string is not empty */
			crit.add(BaseSecuserPeer.TABLE_NAME, "Username", uid,
					Criteria.EQUAL);
			crit.add(BaseSecuserPeer.TABLE_NAME, "Password", pwd,
					Criteria.EQUAL);

			crit.setAll();
			List result = BaseSecuserPeer.doSelect(crit);
			if (result.size() > 0) {
				retVal = (Secuser) result.get(0);
			}
		} catch (TorqueException e) {
			System.out.println("Exception initializing torque.");
			e.printStackTrace();
		} catch (Exception ex) {
			ex.printStackTrace();
		}
		return retVal;
	}
}
