
package com.sns.security.managers;


import org.apache.torque.om.Persistent;

/** 
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Mar 07 11:01:56 CST 2008]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Secuser 
    extends com.sns.security.managers.BaseSecuser
    implements Persistent
{
}
